### ISSUE TITLE
[Todo] Add anime todo list feature

### ISSUE THREAD

**Issue by momu54** [momu54/me#19]
Tasks
- [x] Create `/anime todo` command to show the todo list
- [x] Create a database table or file to save users' todo list
- [x] Add **Add to todo list** button to anime screen
- [x] Released!
