### ISSUE TITLE
[todo] Change anime source

### ISSUE THREAD

**Issue by momu54** [momu54/me#30]
Bahamut only allowed bot's request from Taiwan.
But this bot hosting at other country, so bot gets 403 status every times.

- [ ] Find a API or website can use
- [ ] Check that API can use and get all informations I needed
- [ ] Test API at bot's code
- [ ] Done!
- [ ] Merge branch!

**Comment by momu54** [comment]
This issue will close.
I can't find any other API can use.
So this feature is archive
